package com.cybozu.labs.langdetect.util;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * This is {@link Messages} class generated by Eclipse automatically.
 * Users don't use this class directly.
 * @author Nakatani Shuyo
 */
/* package */ class Messages {
    private static final Logger LOGGER = LoggerFactory.getLogger(Messages.class);

    private static final String BUNDLE_NAME = "com.cybozu.labs.langdetect.util.messages"; //$NON-NLS-1$

    private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

    private Messages() {
    }

    /* package */ static String getString(String key) {
        try {
            return RESOURCE_BUNDLE.getString(key);
        } catch (MissingResourceException e) {
            LOGGER.warn("Missing {} key in messages.properties", key);
            return "!" + key + "!";
        }
    }
}
